# This is a basic workflow to help you get started with Actions
name: CI Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "development" branch
  pull_request:
    branches: ["development"]


jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Code Quality Check
        run: flake8 .

  lint-test:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Run Lint Tests
        run: pylint polls/


  run-tests:
    runs-on: ubuntu-latest
    needs: lint-test  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Run Tests
        run: |
          python manage.py test
